# Form implementation generated from reading ui file 'D:\codeML\project_retail\ui\Login.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(942, 665)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 40, 221, 271))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 50, 191, 201))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\codeML\\project_retail\\ui\\../images/ic_personal.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.groupBoxlogininfor = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBoxlogininfor.setGeometry(QtCore.QRect(260, 40, 431, 261))
        self.groupBoxlogininfor.setObjectName("groupBoxlogininfor")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBoxlogininfor)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 91, 16))
        self.label_2.setObjectName("label_2")
        self.lineEditusername = QtWidgets.QLineEdit(parent=self.groupBoxlogininfor)
        self.lineEditusername.setGeometry(QtCore.QRect(20, 70, 341, 22))
        self.lineEditusername.setObjectName("lineEditusername")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBoxlogininfor)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 91, 16))
        self.label_3.setObjectName("label_3")
        self.lineEditpassword = QtWidgets.QLineEdit(parent=self.groupBoxlogininfor)
        self.lineEditpassword.setGeometry(QtCore.QRect(20, 140, 341, 22))
        self.lineEditpassword.setTabletTracking(False)
        self.lineEditpassword.setAcceptDrops(True)
        self.lineEditpassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditpassword.setDragEnabled(False)
        self.lineEditpassword.setReadOnly(False)
        self.lineEditpassword.setObjectName("lineEditpassword")
        self.checkBoxsaveinfor = QtWidgets.QCheckBox(parent=self.groupBoxlogininfor)
        self.checkBoxsaveinfor.setGeometry(QtCore.QRect(20, 180, 131, 20))
        self.checkBoxsaveinfor.setObjectName("checkBoxsaveinfor")
        self.pushButtonlogin = QtWidgets.QPushButton(parent=self.groupBoxlogininfor)
        self.pushButtonlogin.setGeometry(QtCore.QRect(40, 210, 93, 28))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\codeML\\project_retail\\ui\\../images/ic_login.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonlogin.setIcon(icon)
        self.pushButtonlogin.setObjectName("pushButtonlogin")
        self.pushButtonexit = QtWidgets.QPushButton(parent=self.groupBoxlogininfor)
        self.pushButtonexit.setGeometry(QtCore.QRect(230, 210, 93, 28))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\codeML\\project_retail\\ui\\../images/ic_edit.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonexit.setIcon(icon1)
        self.pushButtonexit.setObjectName("pushButtonexit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 942, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBoxlogininfor.setTitle(_translate("MainWindow", "Login Information:"))
        self.label_2.setText(_translate("MainWindow", "User name:"))
        self.lineEditusername.setText(_translate("MainWindow", "ga@gmail.com"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.lineEditpassword.setText(_translate("MainWindow", "123"))
        self.checkBoxsaveinfor.setText(_translate("MainWindow", "Save Infor"))
        self.pushButtonlogin.setText(_translate("MainWindow", "Login"))
        self.pushButtonexit.setText(_translate("MainWindow", "Exit"))
